export const NEXT_PUBLIC_SUPABASE_URL = process.env.NEXT_PUBLIC_SUPABASE_URL;
export const NEXT_PUBLIC_SUPABASE_ANON_KEY =
  process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY;
export const NEXT_PUBLIC_SUPABASE_REDIRECT_URL =
  process.env.NEXT_PUBLIC_SUPABASE_REDIRECT_URL;

export const SITE_URL = process.env.SITE_URL;
export const SERVICE_ROLE = process.env.SERVICE_ROLE;
