export const NEXT_PUBLIC_SUPABASE_URL = process.env.NEXT_PUBLIC_SUPABASE_URL;
export const NEXT_PUBLIC_SUPABASE_ANON_KEY =
  process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY;
export const NEXT_PUBLIC_SUPABASE_REDIRECT_URL =
  process.env.NEXT_PUBLIC_SUPABASE_REDIRECT_URL;

export const NEXT_PUBLIC_STAKING_GRAPH_URL =
  process.env.NEXT_PUBLIC_STAKING_GRAPH_URL;
export const NEXT_PUBLIC_FACTORY_GRAPH_URL =
  process.env.NEXT_PUBLIC_FACTORY_GRAPH_URL;
export const NEXT_PUBLIC_PORTAL_GRAPH_URL =
  process.env.NEXT_PUBLIC_PORTAL_GRAPH_URL;

export const NEXT_PUBLIC_BLOCKPASS_CLIENT_ID =
  process.env.NEXT_PUBLIC_BLOCKPASS_CLIENT_ID;

export const SUPABASE_SERVICE_KEY = process.env.SUPABASE_SERVICE_KEY;
export const SUPABASE_JWT_SECRET = process.env.SUPABASE_JWT_SECRET;

export const BLOCKPASS_ENDPOINT_SECRET = process.env.BLOCKPASS_ENDPOINT_SECRET;
export const IRON_SESSION_SECRET = process.env.IRON_SESSION_SECRET;
